/**
 * HempForge Data Provenance & Truth Labeling Module
 * 
 * ALCOA+ Compliance: Every output is attributable, legible, contemporaneous,
 * original, accurate, complete, consistent, enduring, and available.
 * 
 * Criterion 1: Every output declares whether it is live, heuristic, or simulated.
 * Criterion 2: Fallback/demo data is labeled and never mixed with production evidence.
 * Criterion 3: Every generated insight stores source inputs, transformation steps,
 *              timestamps, model/formula used, user/service identity, and verification status.
 * Criterion 8: Separates observed data, formula outputs, AI inferences, and speculative hypotheses.
 */

// ─── Output Classification ───────────────────────────────────────────────────

/**
 * Classification of data output fidelity.
 * Every response from HempForge MUST include this classification.
 */
export type OutputClassification =
  | "production-real"      // Live verified data from authenticated sources
  | "deterministic-formula" // Computed from known constants/formulas (e.g., compliance math)
  | "live-ai-inference"    // Real-time AI model output (Gemini/Ollama)
  | "heuristic-fallback"   // Pattern-matching or keyword-based approximation
  | "simulated"            // Canned/demo content when dependencies are unavailable
  | "demo-only";           // Seeded test data that must never enter production

/**
 * Scientific validity classification for model outputs.
 */
export type ScientificClassification =
  | "observed-data"          // Raw instrument/lab data
  | "deterministic-formula"  // Known mathematical formula output
  | "ai-generated-inference" // AI model interpretation/synthesis
  | "speculative-hypothesis"; // Unverified AI speculation

/**
 * Verification status for provenance tracking.
 */
export type VerificationStatus =
  | "verified"          // Confirmed by authoritative source
  | "unverified"        // Not yet confirmed
  | "ai-generated"      // Generated by AI (requires human review)
  | "simulated"         // Not real data
  | "pending-review";   // Awaiting human verification

// ─── Provenance Envelope ─────────────────────────────────────────────────────

/**
 * Complete provenance envelope wrapping any HempForge output.
 * Satisfies ALCOA+ requirements for attributable, contemporaneous, original data.
 */
export interface ProvenanceEnvelope<T = unknown> {
  /** The actual data payload */
  data: T;

  /** How this output was classified */
  outputClassification: OutputClassification;

  /** Scientific validity category */
  scientificClassification: ScientificClassification;

  /** Full provenance chain */
  provenance: {
    /** Who or what produced this output */
    source: {
      type: "user" | "system" | "ai-model" | "external-api" | "formula";
      identity: string;
      version?: string;
    };

    /** What inputs were used */
    inputs: Record<string, unknown>;

    /** Transformation steps applied */
    transformationSteps: string[];

    /** When was this produced */
    timestamp: string;

    /** Which model or formula produced this */
    modelOrFormula: string;

    /** User or service that triggered this */
    triggeredBy: {
      userId: string;
      userRole: string;
      tenantId: string;
    };

    /** Current verification status */
    verificationStatus: VerificationStatus;
  };

  /** Visible disclaimers for the consumer */
  disclaimers: string[];
}

// ─── Factory Functions ───────────────────────────────────────────────────────

/**
 * Create a provenance envelope for live AI inference output.
 */
export function createLiveAIProvenance<T>(
  data: T,
  opts: {
    model: string;
    inputs: Record<string, unknown>;
    steps: string[];
    userId: string;
    userRole: string;
    tenantId: string;
  }
): ProvenanceEnvelope<T> {
  return {
    data,
    outputClassification: "live-ai-inference",
    scientificClassification: "ai-generated-inference",
    provenance: {
      source: { type: "ai-model", identity: opts.model, version: "latest" },
      inputs: opts.inputs,
      transformationSteps: opts.steps,
      timestamp: new Date().toISOString(),
      modelOrFormula: opts.model,
      triggeredBy: {
        userId: opts.userId,
        userRole: opts.userRole,
        tenantId: opts.tenantId,
      },
      verificationStatus: "ai-generated",
    },
    disclaimers: [
      `This output was generated by AI model '${opts.model}' and requires human verification before use in compliance decisions.`,
      "AI-generated content is not a substitute for certified laboratory analysis.",
    ],
  };
}

/**
 * Create a provenance envelope for simulated/fallback output.
 */
export function createSimulatedProvenance<T>(
  data: T,
  opts: {
    reason: string;
    fallbackMethod: string;
    inputs: Record<string, unknown>;
    userId: string;
    userRole: string;
    tenantId: string;
  }
): ProvenanceEnvelope<T> {
  return {
    data,
    outputClassification: "simulated",
    scientificClassification: "speculative-hypothesis",
    provenance: {
      source: { type: "system", identity: "hempforge-fallback-engine" },
      inputs: opts.inputs,
      transformationSteps: [`Fallback triggered: ${opts.reason}`, `Method: ${opts.fallbackMethod}`],
      timestamp: new Date().toISOString(),
      modelOrFormula: opts.fallbackMethod,
      triggeredBy: {
        userId: opts.userId,
        userRole: opts.userRole,
        tenantId: opts.tenantId,
      },
      verificationStatus: "simulated",
    },
    disclaimers: [
      `⚠️ SIMULATED OUTPUT: ${opts.reason}`,
      "This content was generated using fallback heuristics and MUST NOT be used for compliance decisions.",
      "Configure the required API key or service to receive live, verified intelligence.",
    ],
  };
}

/**
 * Create a provenance envelope for deterministic formula output.
 */
export function createFormulaProvenance<T>(
  data: T,
  opts: {
    formula: string;
    inputs: Record<string, unknown>;
    userId: string;
    userRole: string;
    tenantId: string;
  }
): ProvenanceEnvelope<T> {
  return {
    data,
    outputClassification: "deterministic-formula",
    scientificClassification: "deterministic-formula",
    provenance: {
      source: { type: "formula", identity: "hempforge-compliance-engine" },
      inputs: opts.inputs,
      transformationSteps: [`Applied formula: ${opts.formula}`],
      timestamp: new Date().toISOString(),
      modelOrFormula: opts.formula,
      triggeredBy: {
        userId: opts.userId,
        userRole: opts.userRole,
        tenantId: opts.tenantId,
      },
      verificationStatus: "verified",
    },
    disclaimers: [
      "This output is a deterministic calculation from established regulatory formulas.",
    ],
  };
}

/**
 * Create a provenance envelope for heuristic/pattern-matching output.
 */
export function createHeuristicProvenance<T>(
  data: T,
  opts: {
    method: string;
    inputs: Record<string, unknown>;
    userId: string;
    userRole: string;
    tenantId: string;
  }
): ProvenanceEnvelope<T> {
  return {
    data,
    outputClassification: "heuristic-fallback",
    scientificClassification: "speculative-hypothesis",
    provenance: {
      source: { type: "system", identity: "hempforge-heuristic-engine" },
      inputs: opts.inputs,
      transformationSteps: [`Heuristic method: ${opts.method}`],
      timestamp: new Date().toISOString(),
      modelOrFormula: opts.method,
      triggeredBy: {
        userId: opts.userId,
        userRole: opts.userRole,
        tenantId: opts.tenantId,
      },
      verificationStatus: "unverified",
    },
    disclaimers: [
      `This output was generated using keyword-pattern matching (${opts.method}) rather than live AI inference.`,
      "Results should be verified against authoritative sources before compliance use.",
    ],
  };
}

// ─── Demo Data Labeling ──────────────────────────────────────────────────────

/**
 * Mark data as demo/dev artifact with clear provenance.
 * Criterion 2: Demo data must never be mixed into production evidence.
 */
export function labelDemoData<T>(data: T, context: string): ProvenanceEnvelope<T> {
  return {
    data,
    outputClassification: "demo-only",
    scientificClassification: "speculative-hypothesis",
    provenance: {
      source: { type: "system", identity: "hempforge-demo-seed" },
      inputs: {},
      transformationSteps: [`Seeded as demo/dev artifact: ${context}`],
      timestamp: new Date().toISOString(),
      modelOrFormula: "static-seed-data",
      triggeredBy: {
        userId: "system",
        userRole: "system",
        tenantId: "demo",
      },
      verificationStatus: "simulated",
    },
    disclaimers: [
      "⚠️ DEMO DATA: This is a development/testing artifact and must not be used for production compliance decisions.",
      `Context: ${context}`,
    ],
  };
}
