import React, { useCallback, useEffect, useState } from 'react';
import {
  BookMarked, ChevronDown, ChevronRight, Download, FileDown, FileText,
  Loader2, Maximize2, Minimize2, RefreshCw, Search, X,
} from 'lucide-react';

interface PaperRun {
  run_id: string;
  has_md?: boolean;
  has_tex?: boolean;
  has_pdf?: boolean;
  path?: string;
}

export default function PaperViewer() {
  const [runs, setRuns] = useState<PaperRun[]>([]);
  const [selectedRun, setSelectedRun] = useState<string | null>(null);
  const [paperContent, setPaperContent] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [booting, setBooting] = useState(true);
  const [fullscreen, setFullscreen] = useState(false);
  const [format, setFormat] = useState<'md' | 'tex'>('md');
  const [expanded, setExpanded] = useState(true);

  const fetchRuns = useCallback(async () => {
    try {
      const res = await fetch('/api/researchclaw/runs');
      if (res.ok) {
        const data = await res.json();
        const allRuns = (data.runs || []) as PaperRun[];
        const withPapers = allRuns.filter((r) => r.has_md || r.has_tex || r.has_pdf);
        setRuns(withPapers);
      }
    } catch { /* ignore */ }
  }, []);

  useEffect(() => {
    fetchRuns().finally(() => setBooting(false));
  }, [fetchRuns]);

  const loadPaper = useCallback(async (runId: string) => {
    setSelectedRun(runId);
    setLoading(true);
    setPaperContent(null);
    try {
      const res = await fetch(`/api/researchclaw/pipelines/${runId}`);
      if (res.ok) {
        const detail = await res.json();
        if (detail.checkpoint?.paper_path) {
          const paperRes = await fetch(detail.checkpoint.paper_path);
          if (paperRes.ok) {
            setPaperContent(await paperRes.text());
          }
        }
      }
    } catch { /* ignore */ }
    setLoading(false);
  }, []);

  const run = runs.find((r) => r.run_id === selectedRun);

  if (booting) {
    return (
      <div className="border border-white/5 bg-[#111815] p-8 text-center space-y-3">
        <div className="w-8 h-8 mx-auto border-2 border-emerald-400 border-t-transparent animate-spin" />
        <div className="text-sm text-white">Loading papers...</div>
      </div>
    );
  }

  return (
    <div className={`space-y-6 ${fullscreen ? 'fixed inset-0 z-50 bg-black/95 p-6 overflow-y-auto' : ''}`}>
      <header className="border-b border-white/10 pb-6 flex flex-col xl:flex-row xl:items-end justify-between gap-5">
        <div className="space-y-2">
          <h2 className="text-3xl font-display font-bold text-white tracking-tight italic">
            Generated Papers
          </h2>
          <p className="text-white/45 font-mono text-xs uppercase tracking-widest max-w-3xl">
            Papers generated by the ResearchClaw pipeline
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setFullscreen(!fullscreen)}
            className="px-3 py-1.5 text-[10px] font-mono border border-white/10 text-white/70 hover:text-white hover:bg-white/5"
          >
            {fullscreen ? <Minimize2 size={12} className="inline mr-1" /> : <Maximize2 size={12} className="inline mr-1" />}
            {fullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
          </button>
          <button
            onClick={fetchRuns}
            className="px-3 py-1.5 text-[10px] font-mono uppercase tracking-widest border border-white/10 text-white/70 hover:text-white hover:bg-white/5 flex items-center gap-1.5"
          >
            <RefreshCw size={12} />
            Refresh
          </button>
        </div>
      </header>

      <div className="grid grid-cols-1 xl:grid-cols-4 gap-6">
        <div className="border border-white/5 bg-[#111815]">
          <div className="flex items-center justify-between px-5 py-3 border-b border-white/5">
            <div className="text-[10px] font-mono uppercase tracking-[0.2em] text-emerald-400">
              Paper Runs ({runs.length})
            </div>
            <button onClick={() => setExpanded(!expanded)} className="text-slate-500 hover:text-white">
              {expanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
            </button>
          </div>
          {runs.length === 0 ? (
            <div className="p-5 text-center">
              <FileText size={20} className="text-slate-600 mx-auto mb-2" />
              <div className="text-xs text-slate-500">No generated papers yet</div>
            </div>
          ) : (
            <div className="divide-y divide-white/5 max-h-[500px] overflow-y-auto">
              {runs.map((r) => (
                <button
                  key={r.run_id}
                  onClick={() => loadPaper(r.run_id)}
                  className={`w-full text-left px-5 py-3 hover:bg-white/5 transition-colors ${selectedRun === r.run_id ? 'bg-emerald-500/5 border-l-2 border-emerald-500' : ''}`}
                >
                  <div className="text-xs font-mono text-white truncate">{r.run_id}</div>
                  <div className="mt-1 flex gap-2">
                    {r.has_md && <span className="text-[9px] font-mono bg-sky-500/10 text-sky-400 px-1 border border-sky-500/20">MD</span>}
                    {r.has_tex && <span className="text-[9px] font-mono bg-amber-500/10 text-amber-400 px-1 border border-amber-500/20">TEX</span>}
                    {r.has_pdf && <span className="text-[9px] font-mono bg-emerald-500/10 text-emerald-400 px-1 border border-emerald-500/20">PDF</span>}
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>

        <div className={`${fullscreen ? 'xl:col-span-3' : 'xl:col-span-3'} border border-white/5 bg-[#111815]`}>
          <div className="flex items-center justify-between px-5 py-3 border-b border-white/5">
            <div className="flex items-center gap-3">
              <BookMarked size={14} className="text-emerald-400" />
              <span className="text-[10px] font-mono uppercase tracking-[0.2em] text-white/70">
                {selectedRun ? run?.run_id : 'Paper Viewer'}
              </span>
            </div>
            <div className="flex items-center gap-2">
              {run?.has_md && (
                <button
                  onClick={() => setFormat('md')}
                  className={`px-2 py-1 text-[9px] font-mono uppercase tracking-wider ${format === 'md' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'text-slate-500 border border-white/10 hover:text-white'}`}
                >
                  MD
                </button>
              )}
              {run?.has_tex && (
                <button
                  onClick={() => setFormat('tex')}
                  className={`px-2 py-1 text-[9px] font-mono uppercase tracking-wider ${format === 'tex' ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'text-slate-500 border border-white/10 hover:text-white'}`}
                >
                  TEX
                </button>
              )}
            </div>
          </div>
          <div className="p-6 max-h-[700px] overflow-y-auto">
            {loading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 size={20} className="animate-spin text-emerald-400" />
                <span className="ml-2 text-xs text-slate-500">Loading paper...</span>
              </div>
            ) : paperContent ? (
              <pre className="text-xs text-slate-300 font-mono leading-relaxed whitespace-pre-wrap">{paperContent.slice(0, 50000)}</pre>
            ) : (
              <div className="text-center py-12">
                <FileText size={32} className="text-slate-600 mx-auto mb-3" />
                <div className="text-sm text-slate-500">Select a paper run to view its content</div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
